baseURL = "https://links.joshuacasey.net/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"

title = "links.joshuacasey.net"
copyright = "Â© 2025 Joshua Casey"

enableEmoji = true
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params.author]
name = "Joshua Casey"
headline = "Digital Rights Activist & Video Game Streamer"
#image = "https://sharex.dftba.xyz/PNGTuber_Closed-Mouth-Cropped.png"                           # path relative to static directory
image = "/profilepic.jpg"
#image = "/android-chrome-512x512.png"

links = [
    # Streaming
    { twitch = { href = "https://joystick.tv/t/u/joshuaacasey?t=1797a72c", text = "Joystick.tv (18+)" } },
    { twitch = "https://twitch.tv/JoshuaACasey" },

    # Social
    { bluesky = "https://bsky.app/profile/joshuacasey.net" },
    { mastodon = "https://social.dftba.xyz/@JoshuaACasey" },
    #{ instagram = { href = "https://pixelfed.social/JoshuaCasey", text = "Pixelfed", icon = "pixelfed" } },

    # Video Game Clips
    #{ tiktok = "https://www.tiktok.com/@autistic_nerdjc" },
    # Twitch Stream VODs(?)
    #{ youtube = "https://www.youtube.com/c/JoshuaCasey" },

    # Discord Server
    { discord = "https://discord.gg/38JUvfDpMt" },

    # Throne Wishlist
    { amazon = { href = "https://throne.com/joshuaacasey", text = "Throne Wishlist", icon = "gift" } },

    #{ patreon = { href = "https://buymeacoffee.com/joshuaacasey", text="Tip me", icon = "gift" } },

    # Steam Wishlist
    #{ steam = "https://steamcommunity.com/id/JoshuaACasey" },
    { steam = { href = "https://store.steampowered.com/wishlist/id/JoshuaACasey", text = "Steam Wishlist" } },

    # Proton Partner Links
    #{ link = { href = "https://go.getproton.me/SH1pu", text = "Ditch Gmail. Use Proton Mail" } },
    #{ link = { href = "https://go.getproton.me/SH1ph", text = "Protect your passwords with Proton Pass" } },
    #{ link = { href = "https://go.getproton.me/SH1ps", text = "Get around censorship with Proton VPN" } },
    #{ link = { href = "https://go.getproton.me/SH1pc", text = "Protect your precious family photos & files with Proton Drive" } },
    #{ github = "https://github.com/JoshuaACasey" },

    # Business Email
    #{ email = { href = "mailto:contact@joshuacasey.net", text = "Email (Business Only Please!)" } },

    # { link = { href = "https://www.paypal.com/", text = "Tip with Paypal", icon = "" } },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    #     { bluesky = "https://bsky.app/profile/" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    #     { discord = "https://discord.gg/" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    #     { github = "https://github.com/" },
    #     { gitlab = "https://gitlab.com/" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    #     { linkedin = "https://linkedin.com/in/" },
    #     { mastodon = "https://aethy.com/" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #     { steam = "https://steamcommunity.com/id/" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    #     { tiktok = "https://tiktok.com/@" },
    # { tumblr = "https://username.tumblr.com" },
    #     { twitch = "https://twitch.tv/username" },
    #     { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/" },
    #     { youtube = "https://www.youtube.com/c/" },

    # custom links
    #{ link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
    #{ link = { href = "styles/", text = "All the link styles", target = "_self" } },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
